#!/usr/bin/env bun
/**
 * codex MCP bridge — the `codex` MCP child, reimplemented over `codex app-server`.
 *
 * Until 2026-09-28 the child was `codex mcp-server`: codex's own stdio MCP server,
 * exposing two tools, `codex` (start a session with a prompt) and `codex-reply`
 * (continue a thread). Upstream deprecated that subcommand and removed it after
 * codex-cli 0.153.4 (0.154.0+ falls into the interactive TUI and dies with "stdin
 * is not a terminal"), and named `codex app-server` — a JSON-RPC protocol, not
 * MCP — as the replacement. Every coworker skill calls `mcp__codex__codex` /
 * `mcp__codex__codex-reply` (codex-critique is the delivery gate), so the tool
 * contract has to survive the CLI change.
 *
 * This file is that contract: a stdio MCP server the SDK launches like any other
 * child, which advertises the same two tools with the same input schema codex
 * 0.153.4 advertised, and serves each call by driving `codex app-server` through
 * the client the Codex PROVIDER already uses (providers/codex-app-server.ts):
 * initialize → thread/start → turn/start, collecting `item/agentMessage` until
 * `turn/completed`. Threads are kept alive for `codex-reply`; codex persists them
 * on disk, so an evicted thread is `thread/resume`d on a fresh app-server.
 *
 * Boundaries preserved from the old child: the container is the sandbox
 * (`sandbox_mode=danger-full-access`, bwrap off), and git is pinned read-only for
 * the codex process (codex-mcp-server.ts: hooks path + shell env policy) — the
 * app-server inherits this process's env, which the runner composed from the
 * guard vars plus the names-only inherit list.
 *
 * Protocol traffic is stdout; everything logged here goes to stderr.
 */
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';

import {
  attachCodexAutoApproval,
  initializeCodexAppServer,
  killCodexAppServer,
  spawnCodexAppServer,
  startCodexTurn,
  startOrResumeCodexThread,
  tomlBasicString,
  type AppServer,
  type JsonRpcNotification,
  type ThreadParams,
} from './providers/codex-app-server.js';

function log(msg: string): void {
  console.error(`[codex-mcp-bridge] ${msg}`);
}

/** Env var the runner sets: JSON array of `-c key=value` overrides computed in the runner's env. */
export const CODEX_MCP_BRIDGE_OVERRIDES_ENV = 'CODEX_MCP_BRIDGE_OVERRIDES';
/** Per-turn wall clock; a critique that runs longer than this is failed, not hung. */
export const TURN_TIMEOUT_MS =
  Number(process.env.CODEX_MCP_TURN_TIMEOUT_MS) > 0 ? Number(process.env.CODEX_MCP_TURN_TIMEOUT_MS) : 30 * 60_000;
/** A thread's app-server is kept for follow-up `codex-reply` calls this long after its last turn. */
export const THREAD_IDLE_MS =
  Number(process.env.CODEX_MCP_THREAD_IDLE_MS) > 0 ? Number(process.env.CODEX_MCP_THREAD_IDLE_MS) : 15 * 60_000;
/** Live app-servers kept at once; the least recently used one is evicted (its thread can still be resumed). */
export const MAX_LIVE_THREADS = 4;

// ── tool schema: byte-for-byte what codex 0.153.4's `codex mcp-server` advertised ──────────────

export const CODEX_TOOL = {
  name: 'codex',
  description: 'Run a Codex session. Accepts configuration parameters matching the Codex Config struct.',
  inputSchema: {
    type: 'object',
    additionalProperties: false,
    required: ['prompt'],
    properties: {
      'approval-policy': {
        type: 'string',
        enum: ['on-request', 'never'],
        description: 'Approval policy for shell commands generated by the model: `on-request`, `never`.',
      },
      'base-instructions': {
        type: 'string',
        description: 'The set of instructions to use instead of the default ones.',
      },
      'compact-prompt': { type: 'string', description: 'Prompt used when compacting the conversation.' },
      config: {
        type: 'object',
        additionalProperties: true,
        description: 'Individual config settings that will override what is in CODEX_HOME/config.toml.',
      },
      cwd: {
        type: 'string',
        description:
          "Working directory for the session. If relative, it is resolved against the server process's current working directory.",
      },
      'developer-instructions': {
        type: 'string',
        description: 'Developer instructions that should be injected as a developer role message.',
      },
      model: { type: 'string', description: "Optional override for the model name (e.g. 'gpt-5.2', 'gpt-5.2-codex')." },
      prompt: { type: 'string', description: 'The *initial user prompt* to start the Codex conversation.' },
      sandbox: {
        type: 'string',
        enum: ['read-only', 'workspace-write', 'danger-full-access'],
        description: 'Sandbox mode: `read-only`, `workspace-write`, or `danger-full-access`.',
      },
    },
  },
} as const;

export const CODEX_REPLY_TOOL = {
  name: 'codex-reply',
  description: 'Continue a Codex conversation by providing the thread id and prompt.',
  inputSchema: {
    type: 'object',
    required: ['prompt'],
    properties: {
      conversationId: { type: 'string', description: 'DEPRECATED: use threadId instead.' },
      prompt: { type: 'string', description: 'The *next user prompt* to continue the Codex conversation.' },
      threadId: {
        type: 'string',
        description:
          'The thread id for this Codex session. This field is required, but we keep it optional here for backward compatibility for clients that still use conversationId.',
      },
    },
  },
} as const;

export interface CodexToolArgs {
  prompt: string;
  'approval-policy'?: 'on-request' | 'never';
  'base-instructions'?: string;
  'compact-prompt'?: string;
  config?: Record<string, unknown>;
  cwd?: string;
  'developer-instructions'?: string;
  model?: string;
  sandbox?: 'read-only' | 'workspace-write' | 'danger-full-access';
}

export interface CodexReplyArgs {
  prompt: string;
  threadId?: string;
  conversationId?: string;
}

/**
 * Flatten a `config` object into codex `-c key=value` overrides. Nested objects
 * become dotted keys; strings are TOML basic strings; numbers/booleans literal.
 */
export function configToOverrides(config: Record<string, unknown> | undefined, prefix = ''): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(config ?? {})) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v === null || v === undefined) continue;
    if (Array.isArray(v))
      out.push(`${key}=[${v.map((x) => (typeof x === 'string' ? tomlBasicString(x) : String(x))).join(',')}]`);
    else if (typeof v === 'object') out.push(...configToOverrides(v as Record<string, unknown>, key));
    else if (typeof v === 'string') out.push(`${key}=${tomlBasicString(v)}`);
    else out.push(`${key}=${String(v)}`);
  }
  return out;
}

/** The base overrides the runner computed (model provider, sandbox, hooks, git guard shell policy). */
export function runnerOverrides(env: NodeJS.ProcessEnv = process.env): string[] {
  const raw = env[CODEX_MCP_BRIDGE_OVERRIDES_ENV];
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((x): x is string => typeof x === 'string') : [];
  } catch {
    log(`ignoring unparseable ${CODEX_MCP_BRIDGE_OVERRIDES_ENV}`);
    return [];
  }
}

// ── turn collection ─────────────────────────────────────────────────────────────────────────────

export interface TurnResult {
  text: string;
  /** Item count seen during the turn (commands, file changes, reasoning …) — for the stderr summary. */
  items: number;
}

/**
 * Start one turn and collect the agent's final message. Resolves on
 * `turn/completed`, rejects on `turn/failed`, process exit or timeout.
 */
export function runTurn(
  server: AppServer,
  params: { threadId: string; inputText: string; model?: string; cwd?: string },
  timeoutMs: number = TURN_TIMEOUT_MS,
): Promise<TurnResult> {
  return new Promise<TurnResult>((resolve, reject) => {
    let deltas = '';
    let finalText = '';
    let items = 0;
    let settled = false;
    const finish = (fn: () => void): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      const idx = server.notificationHandlers.indexOf(handler);
      if (idx >= 0) server.notificationHandlers.splice(idx, 1);
      server.process.off('exit', onExit);
      fn();
    };
    const onExit = (code: number | null): void =>
      finish(() => reject(new Error(`codex app-server exited (code=${code}) before the turn completed`)));
    const handler = (n: JsonRpcNotification): void => {
      const p = (n.params ?? {}) as Record<string, unknown>;
      switch (n.method) {
        case 'item/agentMessage/delta': {
          const d = p.delta;
          if (typeof d === 'string') deltas += d;
          break;
        }
        case 'item/completed': {
          items += 1;
          const item = p.item as { type?: string; text?: string } | undefined;
          if (item?.type === 'agentMessage' && typeof item.text === 'string' && item.text) finalText = item.text;
          break;
        }
        case 'turn/completed':
          finish(() => resolve({ text: finalText || deltas, items }));
          break;
        case 'turn/failed': {
          const e = p.error as { message?: string } | undefined;
          finish(() => reject(new Error(e?.message || 'codex turn failed')));
          break;
        }
        default:
          break;
      }
    };
    const timer = setTimeout(
      () => finish(() => reject(new Error(`codex turn timed out after ${Math.round(timeoutMs / 1000)}s`))),
      timeoutMs,
    );
    server.notificationHandlers.push(handler);
    server.process.on('exit', onExit);
    startCodexTurn(server, params).catch((err: unknown) =>
      finish(() => reject(err instanceof Error ? err : new Error(String(err)))),
    );
  });
}

// ── thread registry ─────────────────────────────────────────────────────────────────────────────

interface LiveThread {
  server: AppServer;
  overrides: string[];
  model?: string;
  cwd: string;
  lastUsed: number;
  timer: ReturnType<typeof setTimeout>;
}

const live = new Map<string, LiveThread>();

function evict(threadId: string, why: string): void {
  const t = live.get(threadId);
  if (!t) return;
  live.delete(threadId);
  clearTimeout(t.timer);
  log(`thread ${threadId}: app-server released (${why})`);
  try {
    killCodexAppServer(t.server);
  } catch {
    /* already gone */
  }
}

function touch(threadId: string, t: LiveThread): void {
  t.lastUsed = Date.now();
  clearTimeout(t.timer);
  t.timer = setTimeout(() => evict(threadId, 'idle'), THREAD_IDLE_MS);
  t.timer.unref?.();
  while (live.size > MAX_LIVE_THREADS) {
    const oldest = [...live.entries()].sort((a, b) => a[1].lastUsed - b[1].lastUsed)[0];
    if (!oldest || oldest[0] === threadId) break;
    evict(oldest[0], 'lru');
  }
}

async function bootAppServer(overrides: string[]): Promise<AppServer> {
  const server = spawnCodexAppServer(overrides);
  attachCodexAutoApproval(server);
  await initializeCodexAppServer(server);
  return server;
}

function inputWithDeveloperInstructions(prompt: string, dev?: string): string {
  // app-server's turn input has no developer role; the instructions travel at the
  // top of the user turn under an explicit heading so the reviewer contract in
  // codex-critique (sentinel lines within the first 2000 bytes) still holds.
  return dev && dev.trim() ? `Developer instructions:\n${dev.trim()}\n\n${prompt}` : prompt;
}

export async function handleCodex(args: CodexToolArgs): Promise<{ threadId: string; text: string }> {
  if (!args || typeof args.prompt !== 'string' || !args.prompt.trim()) throw new Error('codex: `prompt` is required');
  const overrides = [...runnerOverrides(), ...configToOverrides(args.config)];
  if (args.model) overrides.push(`model=${tomlBasicString(args.model)}`);
  const cwd = args.cwd || process.env.CODEX_MCP_CWD || process.cwd();
  const model = args.model || process.env.CODEX_MODEL || undefined;
  const server = await bootAppServer(overrides);
  let threadId: string;
  try {
    const params = {
      cwd,
      sandbox: 'danger-full-access',
      approvalPolicy: args['approval-policy'] ?? 'never',
      ...(model ? { model } : {}),
      ...(args['base-instructions'] ? { baseInstructions: args['base-instructions'] } : {}),
    } as ThreadParams;
    threadId = await startOrResumeCodexThread(server, undefined, params);
  } catch (err) {
    killCodexAppServer(server);
    throw err;
  }
  const t: LiveThread = { server, overrides, model, cwd, lastUsed: Date.now(), timer: setTimeout(() => undefined, 0) };
  live.set(threadId, t);
  touch(threadId, t);
  const started = Date.now();
  try {
    const r = await runTurn(server, {
      threadId,
      inputText: inputWithDeveloperInstructions(args.prompt, args['developer-instructions']),
      ...(model ? { model } : {}),
      cwd,
    });
    log(
      `thread ${threadId}: turn done in ${Math.round((Date.now() - started) / 1000)}s, ${r.items} item(s), ${r.text.length} chars`,
    );
    touch(threadId, t);
    return { threadId, text: r.text };
  } catch (err) {
    evict(threadId, `turn failed: ${err instanceof Error ? err.message : String(err)}`);
    throw err;
  }
}

export async function handleCodexReply(args: CodexReplyArgs): Promise<{ threadId: string; text: string }> {
  const threadId = (args?.threadId || args?.conversationId || '').trim();
  if (!threadId) throw new Error('codex-reply: `threadId` is required');
  if (!args || typeof args.prompt !== 'string' || !args.prompt.trim())
    throw new Error('codex-reply: `prompt` is required');
  let t = live.get(threadId);
  if (!t) {
    // Evicted or a previous bridge process: codex keeps threads on disk, resume it.
    const overrides = runnerOverrides();
    const server = await bootAppServer(overrides);
    const cwd = process.env.CODEX_MCP_CWD || process.cwd();
    const model = process.env.CODEX_MODEL || undefined;
    try {
      const resumed = await startOrResumeCodexThread(server, threadId, {
        cwd,
        sandbox: 'danger-full-access',
        approvalPolicy: 'never',
        ...(model ? { model } : {}),
      } as ThreadParams);
      if (resumed !== threadId) log(`thread ${threadId} was stale; codex started ${resumed} instead`);
      t = { server, overrides, model, cwd, lastUsed: Date.now(), timer: setTimeout(() => undefined, 0) };
      live.set(resumed, t);
      touch(resumed, t);
      const r = await runTurn(server, { threadId: resumed, inputText: args.prompt, ...(model ? { model } : {}), cwd });
      touch(resumed, t);
      return { threadId: resumed, text: r.text };
    } catch (err) {
      killCodexAppServer(server);
      throw err;
    }
  }
  touch(threadId, t);
  try {
    const r = await runTurn(t.server, {
      threadId,
      inputText: args.prompt,
      ...(t.model ? { model: t.model } : {}),
      cwd: t.cwd,
    });
    touch(threadId, t);
    return { threadId, text: r.text };
  } catch (err) {
    evict(threadId, `reply failed: ${err instanceof Error ? err.message : String(err)}`);
    throw err;
  }
}

// ── MCP server ──────────────────────────────────────────────────────────────────────────────────

export function createBridgeServer(): Server {
  const server = new Server({ name: 'codex-mcp-bridge', version: '1.0.0' }, { capabilities: { tools: {} } });
  server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: [CODEX_TOOL, CODEX_REPLY_TOOL] }));
  server.setRequestHandler(CallToolRequestSchema, async (req) => {
    const name = req.params.name;
    const args = (req.params.arguments ?? {}) as Record<string, unknown>;
    try {
      const r =
        name === 'codex'
          ? await handleCodex(args as unknown as CodexToolArgs)
          : name === 'codex-reply'
            ? await handleCodexReply(args as unknown as CodexReplyArgs)
            : null;
      if (!r) return { isError: true, content: [{ type: 'text', text: `unknown tool: ${name}` }] };
      // Same shape codex's own server returned: the agent's final message as text, and the
      // thread id in structured content so `codex-reply` can continue the conversation.
      return {
        content: [{ type: 'text', text: r.text }],
        structuredContent: { threadId: r.threadId, content: r.text },
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log(`${name} failed: ${msg}`);
      return { isError: true, content: [{ type: 'text', text: `codex bridge: ${msg}` }] };
    }
  });
  return server;
}

async function main(): Promise<void> {
  const server = createBridgeServer();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  log(
    `ready (turn timeout ${Math.round(TURN_TIMEOUT_MS / 1000)}s, thread idle ${Math.round(THREAD_IDLE_MS / 1000)}s, overrides ${runnerOverrides().length})`,
  );
  const shutdown = (): void => {
    for (const id of [...live.keys()]) evict(id, 'bridge exit');
    process.exit(0);
  };
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
  transport.onclose = shutdown;
}

if (import.meta.main) {
  main().catch((err) => {
    log(`fatal: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
