#!/usr/bin/env python3
"""dump-scheduled-tasks — export live scheduled-task DEFINITIONS to a git-trackable file.

Scheduled tasks live only in per-session `inbound.db` rows. Nothing else in the repo
records them, and there is no export/import path. That means an agent's standing
instructions — the ones that decide what a recurring job optimizes for — are a single
SQLite row with no backup and no review trail. Restore an older DB, or recreate a task,
and the current behaviour silently reverts with nothing in git to notice.

Concretely: the learnings-wiki fold's objective was rewritten on 2026-08-04 to stop the
wiki growing without bound. That rewrite exists only in `inbound.db`. Losing it would
undo the fix while every source file still looked correct.

This dumps definitions only. Volatile runtime fields (row_id, process_after, tries,
completed_runs, failed_runs, recent_log, status) are excluded ON PURPOSE so the output
changes when a task's DEFINITION changes and stays byte-identical otherwise — that makes
`git diff` a drift alarm rather than daily noise.

  python3 scripts/dump-scheduled-tasks.py [--repo <path>] [--out <file>] [--md <file>]

ALL-OR-NOTHING. The snapshot is only useful as a drift alarm if a shorter file means
"a task was deleted" and nothing else. A transient `ncl` or SQLite failure on ONE task
must therefore never produce a smaller snapshot: if any listed series cannot be read,
this exits non-zero and leaves the previous snapshot untouched. Partial output would
land in git as an intentional deletion — the exact silent revert this guards against.

Writes are staged to sibling temp files, re-parsed, fsynced, and only then renamed into
place (both files together), so a crash mid-write cannot leave truncated JSON/Markdown.
The artifact records `listed_count` alongside `task_count` so a reader can verify
completeness from the file itself rather than trusting the run that produced it.

Restore is deliberately manual: read the JSON, then `ncl tasks update --id <series>
--prompt "<prompt>"` (or `ncl tasks create` if the series is gone). Auto-apply is not
provided — silently rewriting live agent instructions is exactly the failure mode this
guards against.

Exit codes:
  0  complete snapshot written
  1  one or more listed tasks could not be read — nothing written
  2  could not list tasks at all (host down? bin/ncl missing?) — nothing written
  3  staged output failed validation or could not be committed — nothing replaced
"""
import argparse, json, os, sys, tempfile, subprocess

# Runtime state, not definition. Excluded so the dump is stable across runs.
VOLATILE = {"row_id", "process_after", "tries", "completed_runs", "failed_runs",
            "recent_log", "status", "created_at", "origin_session_id", "id", "ok"}


def ncl(repo, *args):
    """Run `bin/ncl <args>`. Returns (ok, parsed). `ok` is False when the CLI itself
    failed — callers must not confuse that with a successful empty result."""
    try:
        r = subprocess.run([os.path.join(repo, "bin", "ncl"), *args],
                           cwd=repo, capture_output=True, text=True)
    except OSError as e:
        return False, str(e)
    if r.returncode != 0:
        return False, (r.stderr or r.stdout or "").strip()
    try:
        return True, json.loads(r.stdout)
    except Exception:
        return True, r.stdout


def series_ids(repo):
    """`ncl tasks list` has no stable --json contract across versions; parse the table.
    Returns (ok, ids) so a failed list is distinguishable from an empty one."""
    ok, out = ncl(repo, "tasks", "list")
    if not ok:
        return False, out
    if isinstance(out, dict):
        rows = out.get("data") or []
        return True, [r.get("series_id") for r in rows if r.get("series_id")]
    ids = []
    for line in (out or "").splitlines()[1:]:
        tok = line.split()
        if tok and (tok[0].startswith("task-") or "-" in tok[0]):
            ids.append(tok[0])
    return True, ids


def render_md(slug, tasks):
    """Human-readable mirror of the JSON. Every emitted line is right-stripped: prompts
    routinely carry trailing spaces, and committing them makes the snapshot fail
    whitespace lint and produces diff noise unrelated to a definition change. The JSON
    stays byte-exact — it, not this, is the restore source."""
    L = [f"# Scheduled tasks — `{slug}`", "",
         "Generated by `scripts/dump-scheduled-tasks.py`. Definitions only — runtime",
         "state is excluded so a diff here means a task's instructions changed.", "",
         f"{len(tasks)} task(s), complete — the generator exits non-zero rather than",
         "writing a partial snapshot, so a shorter file here means a task was deleted.", ""]
    for t in tasks:
        L += [f"## `{t.get('series_id')}`", "",
              f"- schedule: `{t.get('recurrence') or 'one-shot'}`",
              f"- agent group: `{t.get('agent_group_id')}`", ""]
        if t.get("script"):
            L += ["Pre-task gate:", "", "```bash", str(t["script"]).strip(), "```", ""]
        L += ["Prompt:", "", "```", str(t.get("prompt", "")).strip(), "```", ""]
    body = "\n".join(L) + "\n"
    return "".join(line.rstrip() + "\n" for line in body.splitlines())


def stage(dest, text):
    """Write `text` to a sibling temp file and fsync it. The rename is deferred so a
    multi-file dump commits all-or-nothing. Returns the temp path."""
    d = os.path.dirname(dest) or "."
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=f".{os.path.basename(dest)}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
    except BaseException:
        os.unlink(tmp)
        raise
    return tmp


def commit(staged):
    """Rename every staged temp onto its target, then fsync the containing directories
    so the rename itself survives a crash."""
    for tmp, dest in staged:
        os.replace(tmp, dest)
    for d in {os.path.dirname(dest) or "." for _, dest in staged}:
        fd = os.open(d, os.O_RDONLY)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)


def discard(staged):
    for tmp, _ in staged:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.path.expanduser("~/slang-coworkers-prod/nanoclaw"))
    ap.add_argument("--out", default=None, help="JSON output (default <repo>/docs/scheduled-tasks.<slug>.json)")
    ap.add_argument("--md", default=None, help="optional human-readable markdown output")
    args = ap.parse_args()

    slug = os.environ.get("INSTANCE_SLUG") or os.path.basename(os.path.dirname(args.repo)) or "instance"
    out = args.out or os.path.join(args.repo, "docs", f"scheduled-tasks.{slug}.json")

    listed_ok, ids = series_ids(args.repo)
    if not listed_ok:
        print(f"ERROR: `ncl tasks list` failed: {ids}", file=sys.stderr)
        print("Refusing to touch the existing snapshot.", file=sys.stderr)
        return 2
    if not ids:
        print("no scheduled tasks found (is the host running? is bin/ncl reachable?)", file=sys.stderr)
        print("Refusing to write an empty snapshot over the existing one.", file=sys.stderr)
        return 2

    tasks, failed = [], []
    for sid in ids:
        ok, got = ncl(args.repo, "tasks", "get", "--id", sid, "--json")
        d = got.get("data") if (ok and isinstance(got, dict)) else None
        if not d:
            failed.append((sid, got if not ok else "no `data` in response"))
            continue
        tasks.append({k: v for k, v in sorted(d.items()) if k not in VOLATILE})

    # Fail closed. A snapshot missing a task it just listed is indistinguishable in git
    # from that task having been deleted, so a partial read must never be committed.
    if failed:
        print(f"ERROR: {len(failed)} of {len(ids)} listed task(s) could not be read:", file=sys.stderr)
        for sid, why in failed:
            print(f"  {sid}: {str(why).strip()[:200]}", file=sys.stderr)
        print("\nRefusing to write a partial snapshot — the previous one is still "
              "authoritative.\nRe-run once the host/DB is reachable.", file=sys.stderr)
        return 1

    tasks.sort(key=lambda t: t.get("series_id", ""))
    # `listed_count` is deliberately part of the artifact: a reader can confirm the file
    # is whole without trusting the run that wrote it. No timestamp — the dump must stay
    # byte-identical when no definition changed, or `git diff` stops being a drift alarm.
    payload = {"instance": slug, "complete": True, "listed_count": len(ids),
               "task_count": len(tasks), "tasks": tasks}

    staged = []
    try:
        staged.append((stage(out, json.dumps(payload, indent=2, sort_keys=True) + "\n"), out))
        if args.md:
            staged.append((stage(args.md, render_md(slug, tasks)), args.md))

        # Validate what actually landed on disk, not what we meant to write — a short
        # write or a full disk shows up here, before anything replaces the good copy.
        for tmp, dest in staged:
            text = open(tmp).read()
            if dest == out:
                reread = json.loads(text)
                if reread.get("task_count") != len(tasks) or len(reread.get("tasks", [])) != len(tasks):
                    raise ValueError(f"staged {dest} does not round-trip {len(tasks)} tasks")
            elif not text.strip():
                raise ValueError(f"staged {dest} is empty")

        commit(staged)
    except Exception as e:
        discard(staged)
        print(f"ERROR: could not write snapshot atomically: {e}", file=sys.stderr)
        print("Nothing was replaced.", file=sys.stderr)
        return 3

    print(f"wrote {out}  ({len(tasks)} tasks, complete)")
    if args.md:
        print(f"wrote {args.md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
