#!/usr/bin/env python3
"""dump-scheduled-tasks — export live scheduled-task DEFINITIONS to a git-trackable file.

Scheduled tasks live only in per-session `inbound.db` rows. Nothing else in the repo
records them, and there is no export/import path. That means an agent's standing
instructions — the ones that decide what a recurring job optimizes for — are a single
SQLite row with no backup and no review trail. Restore an older DB, or recreate a task,
and the current behaviour silently reverts with nothing in git to notice.

Concretely: the learnings-wiki fold's objective was rewritten on 2026-08-04 to stop the
wiki growing without bound. That rewrite exists only in `inbound.db`. Losing it would
undo the fix while every source file still looked correct.

This dumps definitions only. Volatile runtime fields (row_id, process_after, tries,
completed_runs, failed_runs, recent_log, status) are excluded ON PURPOSE so the output
changes when a task's DEFINITION changes and stays byte-identical otherwise — that makes
`git diff` a drift alarm rather than daily noise.

  python3 scripts/dump-scheduled-tasks.py [--repo <path>] [--out <file>] [--md <file>]

Restore is deliberately manual: read the JSON, then `ncl tasks update --id <series>
--prompt "<prompt>"` (or `ncl tasks create` if the series is gone). Auto-apply is not
provided — silently rewriting live agent instructions is exactly the failure mode this
guards against.
"""
import argparse, json, os, subprocess, sys

# Runtime state, not definition. Excluded so the dump is stable across runs.
VOLATILE = {"row_id", "process_after", "tries", "completed_runs", "failed_runs",
            "recent_log", "status", "created_at", "origin_session_id", "id", "ok"}


def ncl(repo, *args):
    r = subprocess.run([os.path.join(repo, "bin", "ncl"), *args],
                       cwd=repo, capture_output=True, text=True)
    if r.returncode != 0:
        return None
    try:
        return json.loads(r.stdout)
    except Exception:
        return r.stdout


def series_ids(repo):
    """`ncl tasks list` has no stable --json contract across versions; parse the table."""
    out = ncl(repo, "tasks", "list")
    if isinstance(out, dict):
        rows = out.get("data") or []
        return [r.get("series_id") for r in rows if r.get("series_id")]
    ids = []
    for line in (out or "").splitlines()[1:]:
        tok = line.split()
        if tok and (tok[0].startswith("task-") or "-" in tok[0]):
            ids.append(tok[0])
    return ids


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.path.expanduser("~/slang-coworkers-prod/nanoclaw"))
    ap.add_argument("--out", default=None, help="JSON output (default <repo>/config-examples/scheduled-tasks.<slug>.json)")
    ap.add_argument("--md", default=None, help="optional human-readable markdown output")
    args = ap.parse_args()

    slug = os.environ.get("INSTANCE_SLUG") or os.path.basename(os.path.dirname(args.repo)) or "instance"
    out = args.out or os.path.join(args.repo, "config-examples", f"scheduled-tasks.{slug}.json")

    ids = series_ids(args.repo)
    if not ids:
        print("no scheduled tasks found (is the host running? is bin/ncl reachable?)", file=sys.stderr)
        return 2

    tasks = []
    for sid in ids:
        got = ncl(args.repo, "tasks", "get", "--id", sid, "--json")
        d = (got or {}).get("data") if isinstance(got, dict) else None
        if not d:
            print(f"  WARN: could not read {sid}", file=sys.stderr)
            continue
        tasks.append({k: v for k, v in sorted(d.items()) if k not in VOLATILE})

    tasks.sort(key=lambda t: t.get("series_id", ""))
    payload = {"instance": slug, "task_count": len(tasks), "tasks": tasks}

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {out}  ({len(tasks)} tasks)")

    if args.md:
        L = [f"# Scheduled tasks — `{slug}`", "",
             "Generated by `scripts/dump-scheduled-tasks.py`. Definitions only — runtime",
             "state is excluded so a diff here means a task's instructions changed.", ""]
        for t in tasks:
            L += [f"## `{t.get('series_id')}`", "",
                  f"- schedule: `{t.get('recurrence') or 'one-shot'}`",
                  f"- agent group: `{t.get('agent_group_id')}`", ""]
            if t.get("script"):
                L += ["Pre-task gate:", "", "```bash", str(t["script"]).strip(), "```", ""]
            L += ["Prompt:", "", "```", str(t.get("prompt", "")).strip(), "```", ""]
        with open(args.md, "w") as f:
            f.write("\n".join(L) + "\n")
        print(f"wrote {args.md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
