#!/usr/bin/env python3
"""Unit tests for upsert_pr_body.py (pure functions only; no gh calls)."""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import upsert_pr_body as U

OLD = """## Motivation

A long hand-written description the explanation replaces.

Part of #13073.

<sub>🤖 Generated by an automated Slang coworker — may be inaccurate. A human maintainer should verify.</sub>
"""


class BuildBody(unittest.TestCase):
    def test_replaces_description_keeping_issue_links_and_disclaimer(self):
        body = U.build_body(OLD, "## 📖 Explanation\n\n### Background\nx", "o/r#1", "abc1234def00")
        self.assertTrue(body.startswith("<!-- explain-diff-html:start o/r#1 head=abc1234def00 -->"))
        self.assertIn("### Background", body)
        self.assertNotIn("## Motivation", body)
        self.assertIn("Part of #13073.", body)
        self.assertIn("Generated by an automated Slang coworker", body)
        # Trailer comes after the section.
        self.assertLess(body.index(U.END), body.index("Part of #13073."))

    def test_rerun_is_idempotent_and_replaces_only_the_section(self):
        first = U.build_body(OLD, "## 📖 Explanation v1", "o/r#1", "a" * 12)
        second = U.build_body(first, "## 📖 Explanation v2", "o/r#1", "b" * 12)
        self.assertEqual(second.count("explain-diff-html:start"), 1)
        self.assertIn("v2", second)
        self.assertNotIn("v1", second)
        self.assertEqual(second.count("Part of #13073."), 1)
        self.assertEqual(U.build_body(second, "## 📖 Explanation v2", "o/r#1", "b" * 12), second)

    def test_recognizes_the_issue_link_spellings_we_emit(self):
        for line in ["Fixes #12", "Closes shader-slang/slang#12", "- Refs #9", "**Fixes** #3", "Resolves: #4", "Part of #5."]:
            self.assertEqual(U.trailer_lines(line), [line], line)
        for line in ["fixed the bug in #12's test", "see #12", "Fix the crash"]:
            self.assertEqual(U.trailer_lines(line), [], line)

    def test_empty_old_body(self):
        body = U.build_body("", "## 📖 Explanation", "o/r#1", "c" * 12)
        self.assertTrue(body.rstrip().endswith(U.END))


class QuizPositions(unittest.TestCase):
    def test_spread_out_and_deterministic(self):
        for sha in ["0" * 40, "f" * 40, "84be79e6068bccc4562d791493727f27b009bc3b", "deadbeef"]:
            picks = U.quiz_positions(sha)
            self.assertEqual(len(picks), 5)
            self.assertGreaterEqual(len(set(picks)), 3, picks)
            self.assertLessEqual(max(picks.count(c) for c in picks), 2, picks)
            self.assertEqual(U.quiz_positions(sha), picks)

    def test_not_always_a_across_many_heads(self):
        firsts = {U.quiz_positions(f"{i:040x}")[0] for i in range(50)}
        self.assertGreater(len(firsts), 1)

    def test_three_option_compact_quiz(self):
        picks = U.quiz_positions("abc1234", questions=3, options=3)
        self.assertEqual(sorted(picks), ["A", "B", "C"])


if __name__ == "__main__":
    unittest.main()
