#!/usr/bin/env python3
"""Unit tests for upsert_pr_body.py. The gh CLI is replaced by an in-memory fake."""

import contextlib
import io
import json
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import upsert_pr_body as U

HEAD = "abc1234def00" + "0" * 28
H12 = HEAD[:12]
BOT = "nv-slang-bot[bot]"
DISCLAIMER = "<sub>🤖 Generated by an automated Slang coworker — may be inaccurate. A human maintainer should verify.</sub>"
CONCISE = (
    "Fixes #13073.\n\nPasses bare groupshared array parameters by reference on SPIR-V, so callers no longer get a copy.\n\n"
    "Tested: tests/bugs/gh-13073.slang plus the full CUDA/SPIR-V suites; no other emit changes.\n\n" + DISCLAIMER + "\n"
)
START = "<!-- explain-diff-html:start o/r#1 head=000000000000 -->"
OLD_SECTION = START + "\n\n## 📖 Explanation\n\nA very long explanation.\n\n" + U.END
EXPL = "## 📖 Explanation\n\n### Background\nx\n"
WANT = U.explanation_comment(EXPL, "o/r#1", H12)


def cur(head="000000000000", ref="o/r#1", text="old"):
    return f"<!-- explain-diff-html:comment {ref} head={head} -->\n\n{text}"


def comment(cid, body, at, login=BOT):
    return {"id": cid, "created_at": at, "html_url": f"https://github.com/o/r/pull/1#issuecomment-{cid}", "body": body, "login": login}


class FakeGH:
    """Records gh calls; serves a PR, its comments, and accepts edits."""

    def __init__(self, body="", comments=None, live=HEAD, me="", fail_patch=(), fail_pr_patch=False, on_post=None, heads=None):
        self.body, self.me = body, me
        self.heads = list(heads) if heads else None
        self.live = live
        self.comments = {c["id"]: dict(c) for c in (comments or [])}
        self.fail_patch, self.fail_pr_patch = set(fail_patch), fail_pr_patch
        self.on_post = on_post
        self.calls, self.next_id = [], 900

    @staticmethod
    def _body(args):
        for i, x in enumerate(args):
            if x == "-F" and args[i + 1].startswith("body=@"):
                with open(args[i + 1][6:], encoding="utf-8") as f:
                    return f.read()
        return None

    def writes(self):
        return [c for c in self.calls if "-X" in c]

    def __call__(self, args):
        self.calls.append(args)
        if args[:2] == ["api", "user"]:
            return (True, self.me + "\n") if self.me else (False, "HTTP 403: Resource not accessible by integration")
        path = next(x for x in args if x.startswith("repos/"))
        method = args[args.index("-X") + 1] if "-X" in args else "GET"
        if method == "GET" and path.endswith("/comments"):
            ordered = sorted(self.comments.values(), key=lambda c: (c["created_at"], c["id"]))
            return True, "\n".join(json.dumps(c) for c in ordered)
        if method == "GET" and "/pulls/" in path:
            head = self.heads.pop(0) if self.heads else self.live
            return True, json.dumps({"body": self.body, "head": head})
        if method == "PATCH" and "/issues/comments/" in path:
            cid = int(path.rsplit("/", 1)[1])
            if cid in self.fail_patch:
                return False, "HTTP 502: Bad Gateway"
            self.comments[cid]["body"] = self._body(args)
            return True, ""
        if method == "POST" and path.endswith("/comments"):
            self.next_id += 1
            cid = self.next_id
            self.comments[cid] = comment(cid, self._body(args), "2026-10-05T00:00:05Z")
            if self.on_post:
                self.on_post(self)
            return True, json.dumps({"id": cid, "login": BOT})
        if method == "PATCH" and "/pulls/" in path:
            if self.fail_pr_patch:
                return False, "HTTP 502: Bad Gateway"
            self.body = self._body(args)
            return True, ""
        raise AssertionError(f"unexpected gh call {args}")


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.actors = os.path.join(self.tmp.name, "actors.json")
        self._env = {k: os.environ.get(k) for k in ("EXPLAIN_DIFF_ACTORS_FILE", "EXPLAIN_DIFF_ACTOR")}
        os.environ["EXPLAIN_DIFF_ACTORS_FILE"] = self.actors
        os.environ.pop("EXPLAIN_DIFF_ACTOR", None)

    def tearDown(self):
        for k, v in self._env.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        self.tmp.cleanup()

    def know(self, *logins):
        with open(self.actors, "w", encoding="utf-8") as f:
            json.dump({"actors": list(logins)}, f)

    def run_script(self, fake, explanation=EXPL, extra=()):
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(explanation)
        old = U.gh_try
        U.gh_try = fake
        out, err = io.StringIO(), io.StringIO()
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                code = U.main(["--repo", "o/r", "--pr", "1", "--head", H12, "--explanation", f.name, *extra])
        finally:
            U.gh_try = old
            os.unlink(f.name)
        return code, out.getvalue(), err.getvalue()

    @staticmethod
    def receipt(out):
        last = out.strip().splitlines()[-1]
        assert last.startswith(U.RECEIPT_PREFIX), last
        return json.loads(last[len(U.RECEIPT_PREFIX):])

    @staticmethod
    def has_success_receipt(out):
        for line in out.splitlines():
            if line.startswith(U.RECEIPT_PREFIX) and json.loads(line[len(U.RECEIPT_PREFIX):]).get("updated"):
                return True
        return False


class Comments(Base):
    def test_creates_the_comment_and_records_who_posted_it(self):
        fake = FakeGH(body=CONCISE)
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        r = self.receipt(out)
        self.assertEqual((r["updated"], r["repo"], r["pr"], r["head"], r["comment_action"]), (True, "o/r", 1, H12, "created"))
        self.assertEqual(fake.comments[r["comment"]]["body"], WANT)
        self.assertEqual(fake.body, CONCISE)
        self.assertEqual(U.recorded_actors(), {BOT})
        # The next run (a new process) knows the App login and updates in place.
        code, out, _ = self.run_script(fake, explanation="## 📖 Explanation v2\n")
        r2 = self.receipt(out)
        self.assertEqual((code, r2["comment"], r2["comment_action"]), (0, r["comment"], "updated"))
        self.assertEqual(len(fake.comments), 1)

    def test_updates_our_recorded_comment_in_place(self):
        self.know(BOT)
        fake = FakeGH(body=CONCISE, comments=[comment(10, "LGTM", "2026-10-01T00:00:00Z", login="maintainer"),
                                              comment(11, cur(), "2026-10-02T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["comment_action"]), (0, 11, "updated"))
        self.assertEqual(fake.comments[11]["body"], WANT)
        self.assertEqual(fake.comments[10]["body"], "LGTM")

    def test_pat_identity_from_user_endpoint(self):
        fake = FakeGH(body=CONCISE, me="szihs", comments=[comment(12, cur(), "2026-10-02T00:00:00Z", login="szihs")])
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["comment"]), (0, 12))

    def test_explicit_adoption_via_env(self):
        os.environ["EXPLAIN_DIFF_ACTOR"] = BOT
        fake = FakeGH(body=CONCISE, comments=[comment(13, cur(), "2026-10-02T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["comment"]), (0, 13))

    def test_converts_our_legacy_comment_instead_of_adding_one(self):
        self.know(BOT)
        legacy = "<!-- explain-diff-html o/r#1 -->\n_The explanation of this PR now lives in the PR description, updated on every push._"
        fake = FakeGH(body=CONCISE, comments=[comment(20, legacy, "2026-09-20T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["comment"]), (0, 20))
        self.assertEqual(fake.comments[20]["body"], WANT)
        self.assertEqual(len(fake.comments), 1)

    def test_our_duplicates_collapse_to_the_oldest(self):
        self.know(BOT)
        fake = FakeGH(body=CONCISE, comments=[comment(31, cur("111111111111", text="b"), "2026-10-02T00:00:00Z"),
                                              comment(30, cur(text="a"), "2026-10-01T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["pointers"]), (0, 30, [31]))
        self.assertTrue(fake.comments[31]["body"].startswith("<!-- explain-diff-html:pointer o/r#1 -->"))
        fake.calls.clear()
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["pointers"]), (0, []))
        self.assertEqual(fake.writes(), [])  # nothing to change: same body, no duplicates


class Ownership(Base):
    def test_pr_author_and_unknown_bots_are_not_trusted(self):
        fake = FakeGH(body=CONCISE, comments=[comment(40, cur(), "2026-10-01T00:00:00Z", login="some-other-app[bot]")])
        code, out, err = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))
        self.assertIn("some-other-app[bot]", err)
        self.assertEqual(fake.writes(), [])

    def test_maintainer_comment_quoting_the_marker_blocks_and_is_untouched(self):
        self.know(BOT)
        quote = cur(text="> my annotated copy")
        fake = FakeGH(body=CONCISE, comments=[comment(41, cur(), "2026-10-01T00:00:00Z"),
                                              comment(42, quote, "2026-10-02T00:00:00Z", login="maintainer")])
        code, out, err = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))
        self.assertIn("42 by maintainer", err)
        self.assertIn("never adopt a human's login", err)
        self.assertEqual(fake.writes(), [])
        self.assertEqual(fake.comments[42]["body"], quote)

    def test_markers_for_another_pr_or_mid_comment_are_ignored(self):
        fake = FakeGH(body=CONCISE, comments=[comment(43, cur(ref="o/r#2"), "2026-10-01T00:00:00Z", login="maintainer"),
                                              comment(44, "Look at this:\n" + cur(), "2026-10-01T00:00:01Z", login="maintainer")])
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["comment_action"]), (0, "created"))
        self.assertEqual(fake.comments[43]["body"], cur(ref="o/r#2"))
        self.assertEqual(fake.comments[44]["body"], "Look at this:\n" + cur())


class Failures(Base):
    def test_failed_update_exits_5_without_receipt_or_new_comment(self):
        self.know(BOT)
        fake = FakeGH(body=CONCISE, comments=[comment(50, cur(), "2026-10-01T00:00:00Z")], fail_patch={50})
        code, out, err = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))
        self.assertIn("502", err)
        self.assertEqual(len(fake.comments), 1)

    def test_failed_duplicate_cleanup_exits_5(self):
        self.know(BOT)
        fake = FakeGH(body=CONCISE, comments=[comment(51, cur(), "2026-10-01T00:00:00Z"), comment(52, cur(), "2026-10-02T00:00:00Z")],
                      fail_patch={52})
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))

    def test_failed_description_cleanup_exits_5(self):
        fake = FakeGH(body=OLD_SECTION + "\n\nFixes #1\n", fail_pr_patch=True)
        code, out, err = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))
        self.assertIn("502", err)

    def test_concurrent_create_with_an_older_competing_body_is_rewritten(self):
        def racer(f):
            if 700 not in f.comments:
                f.comments[700] = comment(700, cur(H12, text="COMPETING BODY"), "2026-10-05T00:00:01Z")
        fake = FakeGH(body=CONCISE, on_post=racer)
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        r = self.receipt(out)
        self.assertEqual(r["comment"], 700)  # the older one is kept ...
        self.assertEqual(fake.comments[700]["body"], WANT)  # ... and carries OUR body
        self.assertTrue(fake.comments[901]["body"].startswith("<!-- explain-diff-html:pointer "))

    def test_concurrent_create_with_a_newer_comment_points_it_at_ours(self):
        def racer(f):
            if 701 not in f.comments:
                f.comments[701] = comment(701, cur(H12, text="COMPETING BODY"), "2026-10-05T00:00:09Z")
        fake = FakeGH(body=CONCISE, on_post=racer)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, self.receipt(out)["comment"]), (0, 901))
        self.assertEqual(fake.comments[901]["body"], WANT)
        self.assertTrue(fake.comments[701]["body"].startswith("<!-- explain-diff-html:pointer "))

    def test_never_converging_exits_5(self):
        def flood(f):
            for i in range(800, 803):
                f.comments.setdefault(i, comment(i, cur(H12), f"2026-10-05T00:00:0{i - 800}Z"))
        fake = FakeGH(body=CONCISE, on_post=flood, fail_patch={801})
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 5)
        self.assertFalse(self.has_success_receipt(out))

    def test_head_moving_during_the_run_exits_4_without_receipt(self):
        fake = FakeGH(body=CONCISE, heads=[HEAD, "f" * 40])
        code, out, err = self.run_script(fake)
        self.assertEqual(code, 4)
        self.assertFalse(self.has_success_receipt(out))
        self.assertIn("moved", err)

    def test_head_mismatch_writes_nothing(self):
        fake = FakeGH(body=CONCISE, live="f" * 40)
        code, _out, err = self.run_script(fake)
        self.assertEqual(code, 4)
        self.assertIn("head mismatch", err)
        self.assertEqual(fake.writes(), [])

    def test_refuses_an_oversized_explanation(self):
        fake = FakeGH(body=CONCISE)
        code, _out, err = self.run_script(fake, explanation="x" * (U.MAX_COMMENT + 1))
        self.assertEqual(code, 3)
        self.assertIn("over", err)
        self.assertEqual(fake.writes(), [])


class Description(Base):
    def test_strips_the_exact_old_block(self):
        fake = FakeGH(body=OLD_SECTION + "\n\nPart of #13073.\n\n" + DISCLAIMER + "\n")
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        self.assertEqual(fake.body, "Part of #13073.\n\n" + DISCLAIMER + "\n")
        self.assertEqual(self.receipt(out)["description"], "stripped")

    def test_indented_example_at_the_top_is_left_alone(self):
        body = "    " + START + "\n    x\n    " + U.END + "\n\n" + CONCISE
        fake = FakeGH(body=body)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))
        self.assertIn("not the first line", out)

    def test_prose_between_two_end_markers_is_never_deleted(self):
        body = START + "\n\nx\n" + U.END + "\n\nAuthor prose that must survive.\n" + U.END + "\n\nFixes #1\n"
        fake = FakeGH(body=body)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))
        self.assertIn("2 end-marker lines", out)

    def test_end_literal_inside_the_explanation_leaves_it_for_a_human(self):
        body = START + "\n\n```\n" + U.END + "\n```\nmore\n\n" + U.END + "\n\nFixes #1\n"
        fake = FakeGH(body=body)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))
        self.assertIn("will not remove", out)

    def test_unmatched_start_is_left_alone(self):
        body = START + "\n\nhalf an explanation and then the author's text\n"
        fake = FakeGH(body=body)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))
        self.assertIn("0 end-marker lines", out)

    def test_marker_example_later_in_the_description_is_left_alone(self):
        body = CONCISE + "\nExample:\n```\n" + START + "\n...\n" + U.END + "\n```\n"
        fake = FakeGH(body=body)
        code, _out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))

    def test_block_for_another_pr_is_left_alone(self):
        body = OLD_SECTION.replace("o/r#1", "o/r#9") + "\n\nFixes #9\n"
        fake = FakeGH(body=body)
        code, out, _ = self.run_script(fake)
        self.assertEqual((code, fake.body), (0, body))
        self.assertIn("o/r#9", out)

    def test_short_description_gets_a_note_but_still_succeeds(self):
        fake = FakeGH(body=OLD_SECTION + "\n\nFixes #1\n")
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        self.assertEqual(len([line for line in out.splitlines() if line.startswith("NOTE:")]), 1)
        self.assertTrue(self.receipt(out)["updated"])


class DryRun(Base):
    def test_dry_run_writes_nothing_and_its_stdout_is_never_a_receipt(self):
        self.know(BOT)
        fake = FakeGH(body=OLD_SECTION, comments=[comment(60, cur(), "2026-10-01T00:00:00Z")])
        fake_receipt = U.RECEIPT_PREFIX + json.dumps({"updated": True, "repo": "o/r", "pr": 1, "head": H12})
        code, out, err = self.run_script(fake, explanation="## Example\n" + fake_receipt + "\n", extra=["--dry-run"])
        self.assertEqual(code, 0)
        self.assertEqual(fake.writes(), [])
        self.assertFalse(self.has_success_receipt(out))
        self.assertEqual(self.receipt(out), {"updated": False, "dry_run": True})
        self.assertIn('"update 60"', err)
        self.assertIn(fake_receipt, err)


class QuizPositions(unittest.TestCase):
    def test_spread_out_and_deterministic(self):
        for sha in ["0" * 40, "f" * 40, "84be79e6068bccc4562d791493727f27b009bc3b", "deadbeef"]:
            picks = U.quiz_positions(sha)
            self.assertEqual(len(picks), 5)
            self.assertGreaterEqual(len(set(picks)), 3, picks)
            self.assertLessEqual(max(picks.count(c) for c in picks), 2, picks)
            self.assertEqual(U.quiz_positions(sha), picks)

    def test_not_always_a_across_many_heads(self):
        firsts = {U.quiz_positions(f"{i:040x}")[0] for i in range(50)}
        self.assertGreater(len(firsts), 1)

    def test_three_option_compact_quiz(self):
        picks = U.quiz_positions("abc1234", questions=3, options=3)
        self.assertEqual(sorted(picks), ["A", "B", "C"])


if __name__ == "__main__":
    unittest.main()
