#!/usr/bin/env python3
"""Unit tests for upsert_pr_body.py. The gh CLI is replaced by an in-memory fake."""

import contextlib
import io
import json
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import upsert_pr_body as U

HEAD = "abc1234def00" + "0" * 28
DISCLAIMER = "<sub>🤖 Generated by an automated Slang coworker — may be inaccurate. A human maintainer should verify.</sub>"
CONCISE = (
    "Fixes #13073.\n\nPasses bare groupshared array parameters by reference on SPIR-V, so callers no longer get a copy.\n\n"
    "Tested: tests/bugs/gh-13073.slang plus the full CUDA/SPIR-V suites; no other emit changes.\n\n" + DISCLAIMER + "\n"
)
OLD_SECTION = (
    "<!-- explain-diff-html:start o/r#1 head=000000000000 -->\n\n## 📖 Explanation\n\nA very long explanation.\n\n"
    "<!-- explain-diff-html:end -->"
)


class FakeGH:
    """Records gh calls; serves a PR, its comments, and accepts edits."""

    def __init__(self, body="", comments=None, live=HEAD, uneditable=()):
        self.body, self.live = body, live
        self.comments = {c["id"]: dict(c) for c in (comments or [])}
        self.uneditable = set(uneditable)
        self.calls, self.next_id = [], 900

    @staticmethod
    def _body(args):
        for i, x in enumerate(args):
            if x == "-F" and args[i + 1].startswith("body=@"):
                with open(args[i + 1][6:], encoding="utf-8") as f:
                    return f.read()
        return None

    def __call__(self, args):
        self.calls.append(args)
        path = next(x for x in args if x.startswith("repos/"))
        method = args[args.index("-X") + 1] if "-X" in args else "GET"
        if method == "GET" and path.endswith("/comments"):
            ordered = sorted(self.comments.values(), key=lambda c: c["created_at"])
            return True, "\n".join(json.dumps(c) for c in ordered)
        if method == "GET" and "/pulls/" in path:
            return True, json.dumps({"body": self.body, "head": self.live})
        if method == "PATCH" and "/issues/comments/" in path:
            cid = int(path.rsplit("/", 1)[1])
            if cid in self.uneditable:
                return False, "HTTP 403"
            self.comments[cid]["body"] = self._body(args)
            return True, ""
        if method == "POST" and path.endswith("/comments"):
            self.next_id += 1
            cid = self.next_id
            self.comments[cid] = {"id": cid, "created_at": "2026-10-05T00:00:00Z",
                                  "html_url": f"https://github.com/o/r/pull/1#issuecomment-{cid}", "body": self._body(args)}
            return True, json.dumps({"id": cid, "html_url": self.comments[cid]["html_url"]})
        if method == "PATCH" and "/pulls/" in path:
            self.body = self._body(args)
            return True, ""
        raise AssertionError(f"unexpected gh call {args}")


def comment(cid, body, at):
    return {"id": cid, "created_at": at, "html_url": f"https://github.com/o/r/pull/1#issuecomment-{cid}", "body": body}


class Run(unittest.TestCase):
    def run_script(self, fake, explanation="## 📖 Explanation\n\n### Background\nx\n", extra=()):
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(explanation)
        old = U.gh_try
        U.gh_try = fake
        out, err = io.StringIO(), io.StringIO()
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
                code = U.main(["--repo", "o/r", "--pr", "1", "--head", HEAD[:12], "--explanation", f.name, *extra])
        finally:
            U.gh_try = old
            os.unlink(f.name)
        return code, out.getvalue(), err.getvalue()

    @staticmethod
    def receipt(out):
        return json.loads(out.strip().splitlines()[-1])

    def test_creates_the_comment_when_none_exists(self):
        fake = FakeGH(body=CONCISE)
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        r = self.receipt(out)
        self.assertEqual((r["updated"], r["repo"], r["pr"], r["head"], r["comment_action"]), (True, "o/r", 1, HEAD[:12], "created"))
        made = fake.comments[r["comment"]]["body"]
        self.assertTrue(made.startswith(f"<!-- explain-diff-html:comment o/r#1 head={HEAD[:12]} -->"))
        self.assertIn("### Background", made)
        self.assertEqual(fake.body, CONCISE)  # a concise description is left alone
        self.assertNotIn("NOTE:", out)

    def test_updates_the_existing_marker_comment_in_place(self):
        fake = FakeGH(body=CONCISE, comments=[
            comment(10, "LGTM", "2026-10-01T00:00:00Z"),
            comment(11, "<!-- explain-diff-html:comment o/r#1 head=000000000000 -->\n\nold", "2026-10-02T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["comment_action"]), (0, 11, "updated"))
        self.assertIn(f"head={HEAD[:12]}", fake.comments[11]["body"])
        self.assertEqual(fake.comments[10]["body"], "LGTM")
        self.assertEqual(len(fake.comments), 2)

    def test_converts_a_legacy_comment_instead_of_adding_one(self):
        legacy = "<!-- explain-diff-html o/r#1 -->\n_The explanation of this PR now lives in the PR description, updated on every push._"
        fake = FakeGH(body=CONCISE, comments=[comment(20, legacy, "2026-09-20T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["comment_action"]), (0, 20, "updated"))
        self.assertTrue(fake.comments[20]["body"].startswith("<!-- explain-diff-html:comment "))
        self.assertEqual(len(fake.comments), 1)

    def test_duplicates_collapse_to_the_oldest(self):
        fake = FakeGH(body=CONCISE, comments=[
            comment(31, "<!-- explain-diff-html:comment o/r#1 head=111111111111 -->\n\nb", "2026-10-02T00:00:00Z"),
            comment(30, "<!-- explain-diff-html:comment o/r#1 head=000000000000 -->\n\na", "2026-10-01T00:00:00Z")])
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["pointers"]), (0, 30, [31]))
        self.assertTrue(fake.comments[31]["body"].startswith(U.POINTER_PREFIX))
        self.assertIn("issuecomment-30", fake.comments[31]["body"])
        # A second run touches only the kept comment; the pointer is no longer a candidate.
        fake.calls.clear()
        code, out, _ = self.run_script(fake)
        self.assertEqual((self.receipt(out)["comment"], self.receipt(out)["pointers"]), (30, []))
        self.assertFalse(any("comments/31" in " ".join(c) for c in fake.calls))

    def test_skips_a_candidate_it_cannot_edit(self):
        fake = FakeGH(body=CONCISE, comments=[
            comment(40, "<!-- explain-diff-html:comment o/r#1 head=000000000000 -->\n\nhuman copy", "2026-10-01T00:00:00Z"),
            comment(41, "<!-- explain-diff-html:comment o/r#1 head=111111111111 -->\n\nours", "2026-10-02T00:00:00Z")],
            uneditable={40})
        code, out, _ = self.run_script(fake)
        r = self.receipt(out)
        self.assertEqual((code, r["comment"], r["comment_action"]), (0, 41, "updated"))
        self.assertEqual(len(fake.comments), 2)  # no third comment

    def test_strips_an_old_explanation_section_from_the_description(self):
        fake = FakeGH(body=OLD_SECTION + "\n\nPart of #13073.\n\n" + DISCLAIMER + "\n")
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        self.assertNotIn("explain-diff-html:start", fake.body)
        self.assertNotIn("A very long explanation", fake.body)
        self.assertIn("Part of #13073.", fake.body)
        self.assertIn(DISCLAIMER, fake.body)
        self.assertEqual(self.receipt(out)["description"], "stripped")

    def test_short_description_gets_a_note_but_still_succeeds(self):
        fake = FakeGH(body=OLD_SECTION + "\n\nFixes #1\n")
        code, out, _ = self.run_script(fake)
        self.assertEqual(code, 0)
        note = [l for l in out.splitlines() if l.startswith("NOTE:")]
        self.assertEqual(len(note), 1)
        self.assertIn("gh pr edit 1 -R o/r --body-file", note[0])
        self.assertTrue(self.receipt(out)["updated"])  # receipt stays the last line

    def test_refuses_an_oversized_explanation(self):
        fake = FakeGH(body=CONCISE)
        code, _out, err = self.run_script(fake, explanation="x" * (U.MAX_COMMENT + 1))
        self.assertEqual(code, 3)
        self.assertIn("over", err)
        self.assertFalse(any("-X" in c for c in fake.calls))

    def test_head_mismatch_writes_nothing(self):
        fake = FakeGH(body=CONCISE, live="f" * 40)
        code, _, err = self.run_script(fake)
        self.assertEqual(code, 4)
        self.assertIn("head mismatch", err)
        self.assertFalse(any("-X" in c for c in fake.calls))

    def test_dry_run_writes_nothing(self):
        fake = FakeGH(body=OLD_SECTION, comments=[comment(50, "<!-- explain-diff-html:comment x -->", "2026-10-01T00:00:00Z")])
        code, _out, err = self.run_script(fake, extra=["--dry-run"])
        self.assertEqual(code, 0)
        self.assertIn("[dry-run]", err)
        self.assertIn('"update 50"', err)
        self.assertIn("strip explain-diff section", err)
        self.assertFalse(any("-X" in c for c in fake.calls))


class Helpers(unittest.TestCase):
    def test_pointer_is_never_a_candidate(self):
        self.assertFalse(U.is_candidate(U.pointer_body("o/r#1", "u")))
        self.assertTrue(U.is_candidate("<!-- explain-diff-html o/r#1 -->\nlegacy"))
        self.assertTrue(U.is_candidate("<!-- explain-diff-html:comment o/r#1 head=a -->"))
        self.assertFalse(U.is_candidate("LGTM <!-- explain-diff-html:comment -->"))

    def test_description_strip_is_idempotent(self):
        new, changed, _ = U.description_after_strip(OLD_SECTION + "\n\n" + CONCISE)
        self.assertTrue(changed)
        again, changed2, short = U.description_after_strip(new)
        self.assertEqual((again, changed2, short), (new, False, False))


class QuizPositions(unittest.TestCase):
    def test_spread_out_and_deterministic(self):
        for sha in ["0" * 40, "f" * 40, "84be79e6068bccc4562d791493727f27b009bc3b", "deadbeef"]:
            picks = U.quiz_positions(sha)
            self.assertEqual(len(picks), 5)
            self.assertGreaterEqual(len(set(picks)), 3, picks)
            self.assertLessEqual(max(picks.count(c) for c in picks), 2, picks)
            self.assertEqual(U.quiz_positions(sha), picks)

    def test_not_always_a_across_many_heads(self):
        firsts = {U.quiz_positions(f"{i:040x}")[0] for i in range(50)}
        self.assertGreater(len(firsts), 1)

    def test_three_option_compact_quiz(self):
        picks = U.quiz_positions("abc1234", questions=3, options=3)
        self.assertEqual(sorted(picks), ["A", "B", "C"])


if __name__ == "__main__":
    unittest.main()
