#!/usr/bin/env python3
"""Keep ONE PR comment as the explanation of the PR's current head.

The explanation (GitHub-safe Markdown written by /explain-diff-html) lives in a
single PR comment, marked with COMMENT_MARKER, edited in place on every push. The
PR description stays the author's own concise text (what changed, why, how it was
tested, issue links): squash merges copy the description into git log, so it must
not carry the explanation.

Which comments are ours: only a comment that STARTS with an exact marker for this
repo#pr (the current `:comment` marker, or the `<!-- explain-diff-html <ref> -->`
marker of earlier versions) AND whose author is a bot account, the PR's author, or
the identity `gh api user` reports. A maintainer's comment that quotes the marker
is never touched: a successful edit is not proof of ownership, because the write
role can edit anyone's comment.

What a run does:
  - updates the oldest of our comments in place, or creates one when we have none.
    Our other marker comments become a one-line pointer to it (never deleted).
  - re-reads the comments and reports success only when exactly one of ours carries
    the current marker for the explained head. Any failed write exits 5 without
    the success line, so the freshness gates keep asking for a re-run.
  - removes the explanation block an earlier version wrote at the top of the
    description (`<!-- explain-diff-html:start <this ref> head=… -->` … end marker)
    and nothing else. A block it cannot identify unambiguously is left alone, with
    a NOTE. A description shorter than SHORT_BODY characters also gets a NOTE.

Comment order: GitHub lists comments by creation time and cannot reorder them. The
explanation sits directly after the description when it is the PR's first comment
(run this right after `gh pr create`); otherwise our oldest comment keeps its place.

Head check: the caller passes the commit the explanation was written from
(`git -C <worktree> rev-parse HEAD`). If the PR's live head is a different
commit, the explanation is stale (or the push has not landed) and nothing is
written.

Usage:
  upsert_pr_body.py --repo OWNER/REPO --pr N --head SHA --explanation FILE [--dry-run]
  upsert_pr_body.py --quiz-positions --head SHA [--questions 5] [--options 4]

Exit codes: 0 written (or dry-run printed), 2 usage, 3 over the size limit,
4 head mismatch, 5 gh failure or the comments did not converge to one.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

COMMENT_MARKER = "<!-- explain-diff-html:comment {ref} head={sha} -->"
POINTER_MARKER = "<!-- explain-diff-html:pointer {ref} -->"
_REF = r"([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)#(\d+)"
CURRENT_RE = re.compile(r"<!-- explain-diff-html:comment " + _REF + r" head=([0-9a-f]{7,40}) -->(?:\r?\n|$)")
LEGACY_RE = re.compile(r"<!-- explain-diff-html " + _REF + r" -->(?:\r?\n|$)")
# The block the previous version wrote at the top of the description.
START_LINE_RE = re.compile(r"[ \t]*<!-- explain-diff-html:start " + _REF + r" head=[0-9a-f]{7,40} -->[ \t]*\r?\n")
START_ANY = "<!-- explain-diff-html:start "
END = "<!-- explain-diff-html:end -->"
MAX_COMMENT = 60_000  # GitHub rejects comment bodies over 65,536 characters.
SHORT_BODY = 200

ISSUE_LINK_RE = re.compile(
    r"^\s*(?:[-*]\s*)?(?:\*\*)?(?:fix(?:e[sd])?|close[sd]?|resolve[sd]?|part of|refs?|related to)(?:\*\*)?:?\s+"
    r"(?:[\w.-]+/[\w.-]+)?#\d+",
    re.IGNORECASE,
)
DISCLAIMER_RE = re.compile(r"generated by an automated|^\s*<sub>\s*🤖", re.IGNORECASE)


def same_ref(m: re.Match, repo: str, pr: int) -> bool:
    return m.group(1).lower() == repo.lower() and int(m.group(2)) == pr


def marker_kind(body: str, repo: str, pr: int) -> str | None:
    """'current' / 'legacy' when the body STARTS with our marker for this exact repo#pr."""
    m = CURRENT_RE.match(body or "")
    if m and same_ref(m, repo, pr):
        return "current"
    m = LEGACY_RE.match(body or "")
    if m and same_ref(m, repo, pr):
        return "legacy"
    return None


def is_ours(c: dict, trusted: set[str]) -> bool:
    return c.get("type") == "Bot" or (c.get("login") or "") in trusted


def owned(comments: list[dict], repo: str, pr: int, trusted: set[str]) -> list[dict]:
    """Our marker comments for this PR, oldest first."""
    mine = [c for c in comments if marker_kind(c.get("body") or "", repo, pr) and is_ours(c, trusted)]
    return sorted(mine, key=lambda c: (c.get("created_at") or "", int(c.get("id") or 0)))


def trailer_only(text: str) -> bool:
    return all(ISSUE_LINK_RE.search(s) or DISCLAIMER_RE.search(s) for s in text.splitlines() if s.strip())


def strip_legacy_section(body: str, repo: str, pr: int) -> tuple[str, str]:
    """Remove the explanation block an earlier version wrote at the top of the description.

    Returns (new body, status): 'none', 'stripped', or 'left: <why>' when a block is
    present but cannot be identified unambiguously (the body is then unchanged).
    """
    body = body or ""
    m = START_LINE_RE.match(body)
    if not m:
        return body, ("left: an explain-diff start marker that is not at the top of the description" if START_ANY in body else "none")
    if not same_ref(m, repo, pr):
        return body, f"left: the start marker names {m.group(1)}#{m.group(2)}, not this PR"
    rest = body[m.end():]
    ends = [i.start() for i in re.finditer(re.escape(END), rest)]
    if not ends:
        return body, "left: the start marker has no end marker"
    tail = rest[ends[-1] + len(END):]
    if len(ends) > 1 and not trailer_only(tail):
        return body, "left: several end markers and text after the last one"
    return tail.lstrip("\r\n"), "stripped"


def explanation_comment(explanation: str, ref: str, sha: str) -> str:
    return COMMENT_MARKER.format(ref=ref, sha=sha) + "\n\n" + explanation.strip() + "\n"


def pointer_body(ref: str, keep_url: str) -> str:
    return POINTER_MARKER.format(ref=ref) + f"\n_Superseded: the explanation of this PR is in [this comment]({keep_url}), updated on every push._"


def quiz_positions(sha: str, questions: int = 5, options: int = 4) -> list[str]:
    """Deterministic, spread-out correct-answer letters for a quiz on `sha`.

    Keyed on the head so a re-run of the same head reproduces the same quiz;
    no letter repeats more than twice and at least three letters appear, so the
    correct answer is never "always A".
    """
    letters = "ABCDEFGH"[:options]
    counter = 0
    while True:
        picks = []
        for i in range(questions):
            h = hashlib.sha256(f"{sha}:{counter}:{i}".encode()).digest()
            picks.append(letters[h[0] % options])
        spread = len(set(picks)) >= min(3, options, questions)
        capped = max(picks.count(c) for c in set(picks)) <= max(2, -(-questions // options))
        if spread and capped:
            return picks
        counter += 1


class GhError(Exception):
    pass


def gh_try(args: list[str]) -> tuple[bool, str]:
    r = subprocess.run(["gh", *args], capture_output=True, text=True, check=False)
    if r.returncode != 0:
        return False, r.stderr.strip()[:300]
    return True, r.stdout


def gh(args: list[str]) -> str:
    ok, out = gh_try(args)
    if not ok:
        raise GhError(f"gh {' '.join(args[:4])} failed: {out}")
    return out


def with_body(text: str, args_before: list[str], args_after: list[str] | None = None) -> str:
    """`gh api … -F body=@<tmp> …` with `text` as the body; raises GhError on failure."""
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
        f.write(text)
        tmp = f.name
    try:
        return gh([*args_before, "-F", f"body=@{tmp}", *(args_after or [])])
    finally:
        os.unlink(tmp)


def list_comments(repo: str, pr: int) -> list[dict]:
    out = gh(["api", f"repos/{repo}/issues/{pr}/comments", "--paginate",
              "--jq", ".[] | {id, created_at, html_url, body, login: .user.login, type: .user.type}"])
    return [json.loads(line) for line in out.splitlines() if line.strip()]


def self_login() -> str:
    ok, out = gh_try(["api", "user", "--jq", ".login"])
    return out.strip() if ok else ""


def marker_head(body: str) -> str:
    m = CURRENT_RE.match(body or "")
    return m.group(3) if m else ""


def converge(repo: str, pr: int, ref: str, comment: str, sha: str, trusted: set[str]) -> dict:
    """Make exactly one of our comments carry the explanation for `sha`; returns it. Raises GhError otherwise."""
    for attempt in range(2):
        mine = owned(list_comments(repo, pr), repo, pr, trusted)
        if len(mine) == 1 and marker_kind(mine[0]["body"], repo, pr) == "current" and marker_head(mine[0]["body"]) == sha:
            return mine[0]
        if not mine:
            raise GhError("our explanation comment is missing after writing it")
        if attempt == 1:
            break
        keep, extra = mine[0], mine[1:]
        if marker_head(keep["body"]) != sha:
            with_body(comment, ["api", "-X", "PATCH", f"repos/{repo}/issues/comments/{keep['id']}"], ["--silent"])
        for d in extra:
            with_body(pointer_body(ref, keep.get("html_url") or ""), ["api", "-X", "PATCH", f"repos/{repo}/issues/comments/{d['id']}"], ["--silent"])
    raise GhError(f"our explanation comments on {ref} did not converge to one (a concurrent writer?); re-run")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--repo")
    p.add_argument("--pr", type=int)
    p.add_argument("--head", required=True, help="commit the explanation was written from")
    p.add_argument("--explanation", help="GitHub-safe Markdown file")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--quiz-positions", action="store_true")
    p.add_argument("--questions", type=int, default=5)
    p.add_argument("--options", type=int, default=4)
    a = p.parse_args(argv)

    if a.quiz_positions:
        print(" ".join(quiz_positions(a.head, a.questions, a.options)))
        return 0
    if not (a.repo and a.pr and a.explanation):
        p.error("--repo, --pr and --explanation are required")
    if not re.fullmatch(r"[0-9a-f]{7,40}", a.head):
        p.error("--head must be a commit sha (7-40 hex chars): git -C <worktree> rev-parse HEAD")

    try:
        return run(a)
    except GhError as e:
        print(str(e), file=sys.stderr)
        return 5


def run(a: argparse.Namespace) -> int:
    pr = json.loads(gh(["api", f"repos/{a.repo}/pulls/{a.pr}", "--jq", "{body: .body, head: .head.sha, author: .user.login}"]))
    live = pr.get("head") or ""
    if not live or not live.startswith(a.head):
        print(
            f"head mismatch: explanation written from {a.head[:12]}, PR head is {live[:12]} — "
            "push first, or re-run against the PR's current head",
            file=sys.stderr,
        )
        return 4

    ref = f"{a.repo}#{a.pr}"
    with open(a.explanation, encoding="utf-8") as fh:
        comment = explanation_comment(fh.read(), ref, live[:12])
    if len(comment) > MAX_COMMENT:
        print(f"explanation comment is {len(comment)} chars, over {MAX_COMMENT}: shrink the explanation and re-run", file=sys.stderr)
        return 3

    trusted = {x for x in (pr.get("author") or "", self_login()) if x}
    mine = owned(list_comments(a.repo, a.pr), a.repo, a.pr, trusted)
    new_desc, desc_status = strip_legacy_section(pr.get("body") or "", a.repo, a.pr)
    notes = []
    if desc_status.startswith("left:"):
        notes.append(f"NOTE: the description still holds an explain-diff block this script will not remove ({desc_status[6:]}); "
                     f"move it out by hand with `gh pr edit {a.pr} -R {a.repo} --body-file <file>`.")
    if len(new_desc.strip()) < SHORT_BODY:
        notes.append(f"NOTE: the PR description is {len(new_desc.strip())} chars. Write a concise description "
                     f"(what changed, why, how it was tested, issue links) with `gh pr edit {a.pr} -R {a.repo} --body-file <file>`; "
                     "squash merges copy it into git log, so keep the explanation out of it.")

    if a.dry_run:
        sys.stdout.write(comment)
        plan = {"comment": f"update {mine[0]['id']}" if mine else "create", "pointers": [d["id"] for d in mine[1:]],
                "description": desc_status, "trusted": sorted(trusted), "chars": len(comment)}
        print(f"\n[dry-run] {json.dumps(plan)}", file=sys.stderr)
        for n in notes:
            print(n, file=sys.stderr)
        return 0

    action = "updated"
    if mine:
        with_body(comment, ["api", "-X", "PATCH", f"repos/{a.repo}/issues/comments/{mine[0]['id']}"], ["--silent"])
        for d in mine[1:]:
            with_body(pointer_body(ref, mine[0].get("html_url") or ""), ["api", "-X", "PATCH", f"repos/{a.repo}/issues/comments/{d['id']}"], ["--silent"])
    else:
        made = json.loads(with_body(comment, ["api", "-X", "POST", f"repos/{a.repo}/issues/{a.pr}/comments"],
                                    ["--jq", "{id, login: .user.login}"]))
        if made.get("login"):
            trusted.add(made["login"])
        action = "created"
    kept = converge(a.repo, a.pr, ref, comment, live[:12], trusted)

    if desc_status == "stripped":
        ok, err = True, ""
        try:
            with_body(new_desc, ["api", "-X", "PATCH", f"repos/{a.repo}/pulls/{a.pr}"], ["--silent"])
        except GhError as e:
            ok, err = False, str(e)
        if not ok:
            desc_status = "strip failed"
            notes.append(f"NOTE: could not remove the old explanation block from the description ({err}); re-run to retry.")

    for n in notes:
        print(n)
    # repo/pr/head are echoed so the PostToolUse receipt (pr-auto-map.sh) can name the
    # PR even when the command passed them as shell variables. Keep this the last line,
    # and print it only after the comments converged.
    print(json.dumps({
        "updated": True, "repo": a.repo, "pr": a.pr, "head": live[:12], "chars": len(comment),
        "comment": kept["id"], "comment_action": action, "comment_url": kept.get("html_url") or "",
        "pointers": [d["id"] for d in mine[1:]], "description": desc_status,
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
