#!/usr/bin/env python3
"""Make the PR description the explanation of the PR's current head.

The explanation (GitHub-safe Markdown written by /explain-diff-html) replaces the
PR description. Only the lines the rest of the pipeline depends on survive from
the old description: issue links (`Fixes #N`, `Part of #N`, ...) so GitHub's
auto-close and the chain's PR->issue mapping keep working, and the bot
disclaimer. Re-running replaces the section in place, so the description always
describes one head.

Head check: the caller passes the commit the explanation was written from
(`git -C <worktree> rev-parse HEAD`). If the PR's live head is a different
commit, the explanation is stale (or the push has not landed) and nothing is
written.

Usage:
  upsert_pr_body.py --repo OWNER/REPO --pr N --head SHA --explanation FILE [--dry-run]
  upsert_pr_body.py --quiz-positions --head SHA [--questions 5] [--options 4]

Exit codes: 0 written (or dry-run printed), 2 usage, 3 over the size limit,
4 head mismatch, 5 gh failure.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

START = "<!-- explain-diff-html:start {ref} head={sha} -->"
START_RE = re.compile(r"<!-- explain-diff-html:start [^>]*-->")
END = "<!-- explain-diff-html:end -->"
# The collapsed-comment marker used before the explanation moved into the
# description. A comment carrying it is retired into a one-line pointer.
LEGACY_MARKER = "<!-- explain-diff-html "
MAX_BODY = 60_000  # GitHub rejects bodies over 65,536 characters.

ISSUE_LINK_RE = re.compile(
    r"^\s*(?:[-*]\s*)?(?:\*\*)?(?:fix(?:e[sd])?|close[sd]?|resolve[sd]?|part of|refs?|related to)(?:\*\*)?:?\s+"
    r"(?:[\w.-]+/[\w.-]+)?#\d+",
    re.IGNORECASE,
)
DISCLAIMER_RE = re.compile(r"generated by an automated|^\s*<sub>\s*🤖", re.IGNORECASE)


def strip_section(body: str) -> str:
    """Remove every explain-diff-html section (start..end) from a body."""
    out, i = [], 0
    while True:
        m = START_RE.search(body, i)
        if not m:
            out.append(body[i:])
            break
        out.append(body[i : m.start()])
        end = body.find(END, m.end())
        i = len(body) if end < 0 else end + len(END)
    return "".join(out)


def trailer_lines(old_body: str) -> list[str]:
    """Issue links and the bot disclaimer from the old description, in order, deduplicated."""
    kept: list[str] = []
    for line in strip_section(old_body or "").splitlines():
        s = line.rstrip()
        if (ISSUE_LINK_RE.search(s) or DISCLAIMER_RE.search(s)) and s not in kept:
            kept.append(s)
    return kept


def build_body(old_body: str, explanation: str, ref: str, sha: str) -> str:
    """The new description: the explanation section, then the preserved trailer."""
    section = "\n".join([START.format(ref=ref, sha=sha), "", explanation.strip(), "", END])
    trailer = trailer_lines(old_body)
    return section + ("\n\n" + "\n\n".join(trailer) if trailer else "") + "\n"


def quiz_positions(sha: str, questions: int = 5, options: int = 4) -> list[str]:
    """Deterministic, spread-out correct-answer letters for a quiz on `sha`.

    Keyed on the head so a re-run of the same head reproduces the same quiz;
    no letter repeats more than twice and at least three letters appear, so the
    correct answer is never "always A".
    """
    letters = "ABCDEFGH"[:options]
    counter = 0
    while True:
        picks = []
        for i in range(questions):
            h = hashlib.sha256(f"{sha}:{counter}:{i}".encode()).digest()
            picks.append(letters[h[0] % options])
        spread = len(set(picks)) >= min(3, options, questions)
        capped = max(picks.count(c) for c in set(picks)) <= max(2, -(-questions // options))
        if spread and capped:
            return picks
        counter += 1


def gh(args: list[str], stdin: str | None = None) -> str:
    r = subprocess.run(["gh", *args], input=stdin, capture_output=True, text=True, check=False)
    if r.returncode != 0:
        print(f"gh {' '.join(args[:3])} failed: {r.stderr.strip()[:300]}", file=sys.stderr)
        sys.exit(5)
    return r.stdout


def retire_legacy_comment(repo: str, pr: int, dry_run: bool) -> str:
    """Point an old collapsed explanation comment at the description. Returns what happened."""
    pointer = (
        f"{LEGACY_MARKER}{repo}#{pr} -->\n"
        "_The explanation of this PR now lives in the PR description, updated on every push._"
    )
    jq = f'.[] | select((.body // "") | startswith("{LEGACY_MARKER}")) | select(.body != {json.dumps(pointer)}) | .id'
    ids = gh(["api", f"repos/{repo}/issues/{pr}/comments", "--paginate", "--jq", jq]).split()
    for cid in ids:
        if not dry_run:
            gh(["api", "-X", "PATCH", f"repos/{repo}/issues/comments/{cid}", "-f", f"body={pointer}", "--silent"])
    return f"retired {','.join(ids)}" if ids else "none"


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--repo")
    p.add_argument("--pr", type=int)
    p.add_argument("--head", required=True, help="commit the explanation was written from")
    p.add_argument("--explanation", help="GitHub-safe Markdown file")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--quiz-positions", action="store_true")
    p.add_argument("--questions", type=int, default=5)
    p.add_argument("--options", type=int, default=4)
    a = p.parse_args(argv)

    if a.quiz_positions:
        print(" ".join(quiz_positions(a.head, a.questions, a.options)))
        return 0
    if not (a.repo and a.pr and a.explanation):
        p.error("--repo, --pr and --explanation are required")
    if not re.fullmatch(r"[0-9a-f]{7,40}", a.head):
        p.error("--head must be a commit sha (7-40 hex chars): git -C <worktree> rev-parse HEAD")

    pr = json.loads(gh(["api", f"repos/{a.repo}/pulls/{a.pr}", "--jq", "{body: .body, head: .head.sha}"]))
    live = pr.get("head") or ""
    if not live or not live.startswith(a.head):
        print(
            f"head mismatch: explanation written from {a.head[:12]}, PR head is {live[:12]} — "
            "push first, or re-run against the PR's current head",
            file=sys.stderr,
        )
        return 4

    with open(a.explanation, encoding="utf-8") as fh:
        explanation = fh.read()
    body = build_body(pr.get("body") or "", explanation, f"{a.repo}#{a.pr}", live[:12])
    if len(body) > MAX_BODY:
        print(f"body is {len(body)} chars, over {MAX_BODY}: shrink the explanation and re-run", file=sys.stderr)
        return 3
    if a.dry_run:
        sys.stdout.write(body)
        print(f"\n[dry-run] {len(body)} chars; legacy: {retire_legacy_comment(a.repo, a.pr, True)}", file=sys.stderr)
        return 0

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
        f.write(body)
        tmp = f.name
    try:
        gh(["api", "-X", "PATCH", f"repos/{a.repo}/pulls/{a.pr}", "-F", f"body=@{tmp}", "--silent"])
    finally:
        os.unlink(tmp)
    legacy = retire_legacy_comment(a.repo, a.pr, False)
    print(json.dumps({"updated": True, "chars": len(body), "head": live[:12], "legacy_comment": legacy}))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
