// Integration tests for container/hooks/gate-pr-description.sh (+ lib/pr_description.py).
//
// A PR description stays short because squash merges copy it into git log: each
// section at most 2 lines, at most 1,000 characters, no tables. The hook reads
// the description from the Bash command (inline, heredoc, $(cat …), or a file)
// and refuses one that breaks the limits with one line on stderr.

import { spawnSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const SCRIPT = path.resolve(process.cwd(), 'container', 'hooks', 'gate-pr-description.sh');

let tmp: string;

beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'gate-pr-desc-'));
});

afterEach(() => {
  fs.rmSync(tmp, { recursive: true, force: true });
});

function run(command: string, env: Record<string, string> = {}, toolName = 'Bash') {
  const proc = spawnSync('bash', [SCRIPT], {
    input: JSON.stringify({ tool_name: toolName, tool_input: { command }, cwd: tmp }),
    env: { PATH: process.env.PATH || '', HOME: tmp, ...env },
    encoding: 'utf-8',
  });
  return { status: proc.status ?? -1, stderr: (proc.stderr ?? '').trim() };
}

// The shape of shader-slang/slang#13450 (3,917 chars): a 5-line Risk list, a table
// and a long open-question block in the description.
const LONG = [
  '**Summary.** `DownstreamArgs` given at different levels no longer replace each other.',
  '',
  '**Root cause.** `CompilerOptionSet::overrideWith` merges `DownstreamArgs` through `add()`.',
  '',
  '**Tests.** `slang-static-unit-test` covers the merge rules.',
  '',
  '**Risk.** The change affects every consumer of `DownstreamArgs` composition:',
  '- **Repeats reach the tool.** An argument given at two levels now reaches the tool twice.',
  '- **Session digest.** `getSessionDescDigest` changes for sessions with `DownstreamArgs`.',
  '- **Record-replay.** Streams recorded on older builds carry a target copy of the session args.',
  '- **Unchanged.** The precompile path builds its own `TargetRequest` and composite.',
  '',
  '**Open question for maintainers (blocks merge).** The issue asks for a defined precedence.',
  '',
  '| Arguments | Before | After |',
  '|---|---|---|',
  '| session `--fmad=true`, link `--fmad=false` | link silently wins | NVRTC: defined more than once |',
  '',
  'Options: (1) keep this behaviour; (2) define a precedence. ' + 'x'.repeat(2400),
  '',
  'Fixes #13436',
  '',
  '<sub>🤖 Generated by an automated Slang coworker — may be inaccurate.</sub>',
].join('\n');

const OK = [
  '**Summary.** Downstream args at all levels now reach the tool, in order.',
  '**Root cause.** add() matched entries by tool name, so later levels replaced earlier ones.',
  '**Tests.** Unit tests cover the merge rules and three NVRTC cases.',
  '**Risk.** Repeated flags now reach the tool twice; NVRTC rejects some.',
  'Open question (blocks merge): which level wins on a conflict — details in the explanation comment.',
  '',
  'Fixes #13436',
  '',
  '<sub>🤖 Generated by an automated Slang coworker — may be inaccurate.</sub>',
].join('\n');

const heredocCreate = (body: string) =>
  `gh pr create -R shader-slang/slang --draft --title "x" --body "$(cat <<'EOF'\n${body}\nEOF\n)"`;

describe('gate-pr-description.sh', () => {
  it('refuses a #13450-shaped description and says what is over, on one line', () => {
    const r = run(heredocCreate(LONG));
    expect(r.status).toBe(2);
    expect(r.stderr.split('\n')).toHaveLength(1);
    expect(r.stderr).toContain('Risk has 5 lines, max 2');
    expect(r.stderr).toContain('it contains a table');
    expect(r.stderr).toMatch(/total [\d,]+ chars, max 1,000/);
    expect(r.stderr).toContain('explanation comment (/explain-diff-html)');
  });

  it('allows a compliant description (disclaimer and Fixes lines not counted)', () => {
    expect(run(heredocCreate(OK)).status).toBe(0);
  });

  it('refuses a table even in a short description', () => {
    const body = '**Summary.** Short.\n\n| a | b |\n|---|---|\n| 1 | 2 |';
    const r = run(heredocCreate(body));
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('it contains a table');
  });

  it('refuses a section with 3 lines and allows one with 2', () => {
    const three = '**Risk.** One.\n- two\n- three';
    expect(run(heredocCreate(three)).stderr).toContain('Risk has 3 lines, max 2');
    expect(run(heredocCreate('**Risk.** One.\n- two')).status).toBe(0);
  });

  it('counts ## headings as sections too', () => {
    const r = run(heredocCreate('## Summary\nline one\nline two\n'));
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('Summary has 3 lines, max 2');
  });

  it('reads --body-file from a file, and a file this same command writes', () => {
    const f = path.join(tmp, 'desc.md');
    fs.writeFileSync(f, LONG);
    expect(run(`gh pr edit 13450 -R shader-slang/slang --body-file ${f}`).status).toBe(2);
    fs.writeFileSync(f, OK);
    expect(run(`gh pr edit 13450 -R shader-slang/slang -F ${f}`).status).toBe(0);
    const g = path.join(tmp, 'new.md');
    expect(run(`cat > ${g} <<'EOF'\n${LONG}\nEOF\ngh pr edit 13450 --body-file ${g}`).status).toBe(2);
    expect(run(`cat > ${g} <<'EOF'\n${OK}\nEOF\ngh pr edit 13450 --body-file ${g}`).status).toBe(0);
  });

  it('reads --body-file - from a heredoc on the same command', () => {
    expect(run(`gh pr create --title x --body-file - <<'EOF'\n${LONG}\nEOF`).status).toBe(2);
    expect(run(`gh pr create --title x --body-file - <<'EOF'\n${OK}\nEOF`).status).toBe(0);
  });

  it('reads an inline --body and a $(cat FILE) body', () => {
    expect(run(`gh pr edit 5 --body "**Risk.** a\n- b\n- c"`).stderr).toContain('Risk has 3 lines');
    const f = path.join(tmp, 'd.md');
    fs.writeFileSync(f, LONG);
    expect(run(`gh pr edit 5 --body "$(cat ${f})"`).status).toBe(2);
  });

  it('checks gh api pulls bodies (-f body=, -F body=@file) and ignores comment endpoints', () => {
    const f = path.join(tmp, 'b.md');
    fs.writeFileSync(f, LONG);
    expect(run(`gh api -X PATCH repos/shader-slang/slang/pulls/13450 -F body=@${f}`).status).toBe(2);
    expect(run(`gh api -X PATCH repos/shader-slang/slang/pulls/13450 -f body='**Summary.** ok'`).status).toBe(0);
    expect(run(`gh api -X POST repos/shader-slang/slang/issues/13450/comments -F body=@${f}`).status).toBe(0);
    expect(run(`gh api -X POST repos/shader-slang/slang/pulls/13450/comments -F body=@${f}`).status).toBe(0);
  });

  it('lets body-less edits through (title, labels, reviewers)', () => {
    expect(run('gh pr edit 13450 --title "new title" --add-label "pr: non-breaking"').status).toBe(0);
    expect(run('gh pr edit 13450 --add-reviewer someone').status).toBe(0);
    expect(run('gh pr ready 13450 && gh pr view 13450').status).toBe(0);
    expect(run('gh pr create --help').status).toBe(0);
  });

  it('refuses gh pr create whose description comes from --fill*, --template, --editor, --recover or a prompt', () => {
    for (const flags of [
      '--fill --draft',
      '--fill-first',
      '--fill-verbose',
      '--template pr.md',
      '-T pr.md',
      '--editor',
      '--recover x.json',
      '--title x',
    ]) {
      const r = run(`gh pr create ${flags}`);
      expect(r.status, flags).toBe(2);
      expect(r.stderr, flags).toContain('--body-file <absolute path>');
    }
  });

  it('finds the gh api endpoint past option values and reads --input=FILE (#4)', () => {
    const f = path.join(tmp, 'long.md');
    fs.writeFileSync(f, LONG);
    expect(run(`gh api -X PATCH -H 'Accept: application/vnd.github+json' repos/o/r/pulls/1 -F body=@${f}`).status).toBe(
      2,
    );
    const j = path.join(tmp, 'payload.json');
    fs.writeFileSync(j, JSON.stringify({ body: LONG }));
    expect(run(`gh api --method=PATCH repos/o/r/pulls/1 --input=${j}`).status).toBe(2);
    fs.writeFileSync(j, JSON.stringify({ body: OK }));
    expect(run(`gh api --method=PATCH repos/o/r/pulls/1 --input=${j}`).status).toBe(0);
  });

  it('never reads a stale file this same command overwrites (#5)', () => {
    const f = path.join(tmp, 'desc.md');
    fs.writeFileSync(f, OK);
    const r = run(`printf '%s\\n' '**Risk.** one' '- two' '- three' > ${f}; gh pr edit 1 -F ${f}`);
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('writes');
  });

  it('allows a literal $ or backtick inside a single-quoted body (#6)', () => {
    expect(run("gh pr edit 1 --body '**Summary.** costs $5 and names `foo`.'").status).toBe(0);
  });

  it('resolves a relative cd and a piped heredoc on stdin (#7)', () => {
    fs.mkdirSync(path.join(tmp, 'reports'));
    fs.writeFileSync(path.join(tmp, 'reports', 'desc.md'), OK);
    expect(run('cd reports && gh pr edit 1 --body-file desc.md').status).toBe(0);
    expect(run(`cat <<'EOF' | gh pr create --title x --body-file -\n${OK}\nEOF`).status).toBe(0);
    expect(run(`cat <<'EOF' | gh pr create --title x --body-file -\n${LONG}\nEOF`).status).toBe(2);
  });

  it('counts a table without outer pipes (#8)', () => {
    const r = run(heredocCreate('**Summary.** Short.\n\nA | B\n--- | ---\n1 | 2'));
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('it contains a table');
    expect(run(heredocCreate('**Summary.** a | b, then ---.')).status).toBe(0);
  });

  it('excludes only a final <sub> disclaimer and exact closing lines (#9)', () => {
    const sub = `<sub>${'x'.repeat(1200)}</sub>`;
    expect(run(heredocCreate(`${sub}\n\n**Summary.** Short.`)).status).toBe(2);
    expect(run(heredocCreate(`Fixes the entire analysis in #1 ${'y'.repeat(1200)}`)).status).toBe(2);
    expect(run(heredocCreate('**Summary.** Short.\n\nFixes #1, closes o/r#2.\n\n<sub>bot</sub>')).status).toBe(0);
  });

  it('refuses a description it cannot read, asking for an absolute --body-file', () => {
    let r = run('gh pr edit 13450 --body "$DESC"');
    expect(r.status).toBe(2);
    expect(r.stderr).toContain('--body-file <absolute path>');
    r = run('gh pr edit 13450 --body-file notes/missing.md');
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("can't be read");
  });

  it('is off with PR_DESCRIPTION_GATE=0, and the limits are tunable', () => {
    expect(run(heredocCreate(LONG), { PR_DESCRIPTION_GATE: '0' }).status).toBe(0);
    const env = { PR_DESCRIPTION_MAX_CHARS: '100000', PR_DESCRIPTION_MAX_SECTION_LINES: '20' };
    const body = '**Risk.** One.\n- two\n- three';
    expect(run(heredocCreate(body), env).status).toBe(0);
  });

  it('ignores other tools and unrelated commands', () => {
    expect(run(heredocCreate(LONG), {}, 'Write').status).toBe(0);
    expect(run('git push origin HEAD && echo gh pr create later').status).toBe(0);
    expect(run('ls -la').status).toBe(0);
  });
});
