import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import { commandText, slashCommandName, withoutBotSuffix } from './slash-command.js';

describe('canonical slash-command parse', () => {
  it('is generated byte-for-byte into the runner tree', () => {
    const root = process.cwd();
    const source = fs.readFileSync(path.join(root, 'src/slash-command.ts'), 'utf8');
    expect(fs.readFileSync(path.join(root, 'container/agent-runner/src/slash-command.generated.ts'), 'utf8')).toBe(
      source,
    );
  });

  it.each([
    ['/clear', '/clear'],
    ['/Clear some args', '/clear'],
    ['/clear@somebot', '/clear'],
    ['/clear@somebot args', '/clear'],
    ['/clear\tx', '/clear'],
    ['/clearx', '/clearx'],
    ['/clear.', '/clear.'],
    ['/clear@', '/clear@'],
    ['/clear@bot.', '/clear@bot.'],
    ['/clear@bot@bot', '/clear@bot@bot'],
    ['/@somebot', '/@somebot'],
    ['/workspace/reports@2026/summary.md explain', '/workspace/reports@2026/summary.md'],
    ['/Users/me/node_modules/@types/node why', '/users/me/node_modules/@types/node'],
    ['clear', null],
    [' /clear', null],
    ['', null],
  ])('names %j as %j', (text, name) => {
    expect(slashCommandName(text)).toBe(name);
  });

  it.each([
    ['{"text":"  /clear  "}', '/clear'],
    ['  /clear  ', '/clear'],
    ['{"text":5}', ''],
    ['{"other":"/clear"}', ''],
    ['"/clear"', ''],
    ['null', ''],
  ])('reads command text from %j', (content, text) => {
    expect(commandText(content)).toBe(text);
  });

  it.each([
    ['/compact@SomeBot keep the plan', '/compact keep the plan'],
    ['/Compact@bot', '/Compact'],
    ['/compact', '/compact'],
    ['/compact keep a@b', '/compact keep a@b'],
    ['hello @bot', 'hello @bot'],
    ['/workspace/reports@2026/summary.md explain', '/workspace/reports@2026/summary.md explain'],
    ['/Users/me/node_modules/@types/node why', '/Users/me/node_modules/@types/node why'],
    ['/clear@bot.', '/clear@bot.'],
  ])('dispatches %j as %j', (text, dispatched) => {
    expect(withoutBotSuffix(text)).toBe(dispatched);
  });
});
